/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ProductLazyImport = createFileRoute('/product')()
const GalleryLazyImport = createFileRoute('/gallery')()
const ELabsChallengesLazyImport = createFileRoute('/e-labs-challenges')()

// Create/Update Routes

const ProductLazyRoute = ProductLazyImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/product.lazy').then((d) => d.Route))

const GalleryLazyRoute = GalleryLazyImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/gallery.lazy').then((d) => d.Route))

const ELabsChallengesLazyRoute = ELabsChallengesLazyImport.update({
  id: '/e-labs-challenges',
  path: '/e-labs-challenges',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/e-labs-challenges.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/e-labs-challenges': {
      id: '/e-labs-challenges'
      path: '/e-labs-challenges'
      fullPath: '/e-labs-challenges'
      preLoaderRoute: typeof ELabsChallengesLazyImport
      parentRoute: typeof rootRoute
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryLazyImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-labs-challenges': typeof ELabsChallengesLazyRoute
  '/gallery': typeof GalleryLazyRoute
  '/product': typeof ProductLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-labs-challenges': typeof ELabsChallengesLazyRoute
  '/gallery': typeof GalleryLazyRoute
  '/product': typeof ProductLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/e-labs-challenges': typeof ELabsChallengesLazyRoute
  '/gallery': typeof GalleryLazyRoute
  '/product': typeof ProductLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e-labs-challenges' | '/gallery' | '/product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e-labs-challenges' | '/gallery' | '/product'
  id: '__root__' | '/' | '/e-labs-challenges' | '/gallery' | '/product'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ELabsChallengesLazyRoute: typeof ELabsChallengesLazyRoute
  GalleryLazyRoute: typeof GalleryLazyRoute
  ProductLazyRoute: typeof ProductLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ELabsChallengesLazyRoute: ELabsChallengesLazyRoute,
  GalleryLazyRoute: GalleryLazyRoute,
  ProductLazyRoute: ProductLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/e-labs-challenges",
        "/gallery",
        "/product"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/e-labs-challenges": {
      "filePath": "e-labs-challenges.lazy.tsx"
    },
    "/gallery": {
      "filePath": "gallery.lazy.tsx"
    },
    "/product": {
      "filePath": "product.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
